name: reviewdog

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Format code
      run: cargo fmt
    
    - name: suggester / rustfmt
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: rustfmt
